apiVersion: v1
kind: Service
metadata:
  name: {appname}-svc
  namespace: {namespace}
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: {appname}
    uid: {uid}
  selfLink: /api/v1/namespaces/{namespace}/services/{appname}-svc
spec:
  clusterIP: None
  ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  - name: spark-ui
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    spark-app-selector: {appid}
    spark-role: driver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
