apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-app-selector: spark-appid-test1
    spark-role: driver
  name: spark-appname-test1
  namespace: dev
  resourceVersion: "1542244"
  selfLink: /api/v1/namespaces/dev/pods/spark-appname-test1
spec:
  containers:
  - args:
    - driver-py
    - --properties-file
    - /opt/spark/conf/spark.properties
    - --class
    - org.apache.spark.deploy.PythonRunner
    env:
    - name: SPARK_DRIVER_BIND_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SPARK_LOCAL_DIRS
      value: /var/data/spark-58c2dd88-e4d2-4f16-9381-531937827f9e
    - name: PYSPARK_PRIMARY
      value: hdfs:///user/hadoop/etlsdk/run.py
    - name: PYSPARK_MAJOR_PYTHON_VERSION
      value: "3"
    - name: PYSPARK_APP_ARGS
      value: data_pipeline.plugin_base.oss2hive.Oss2HivePlugin.run --config hdfs://apps/ETLPlatform/production/1711673/configs.json
    - name: PYSPARK_FILES
      value: file:///opt/spark/work-dir/data_pipeline.zip:file:///opt/spark/work-dir/etlsdk.zip
    - name: SPARK_CONF_DIR
      value: /opt/spark/conf
    image: registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline:test
    imagePullPolicy: Always
    name: spark-kubernetes-driver
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    resources:
      limits:
        memory: 800Mi
      requests:
        cpu: "0.2"
        memory: 800Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/data/spark-58c2dd88-e4d2-4f16-9381-531937827f9e
      name: spark-local-dir-1
    - mountPath: /opt/spark/conf
      name: spark-conf-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: spark-token-zr5xz
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: aliyun-registry
  nodeName: sa3.k8s.aipp.io
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: spark
  serviceAccountName: spark
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: spark-local-dir-1
  - configMap:
      defaultMode: 420
      name: spark-appname-test1-conf-map
    name: spark-conf-volume
  - name: spark-token-zr5xz
    secret:
      defaultMode: 420
      secretName: spark-token-zr5xz
