apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 20.100.2.155/32
  creationTimestamp: 2019-09-10T02:55:00Z
  labels:
    spark-app-selector: spark-appid-test1
    spark-role: driver
  name: datapipeline-1568084099332-driver
  namespace: dev
  resourceVersion: "1542244"
  selfLink: /api/v1/namespaces/dev/pods/datapipeline-1568084099332-driver
  uid: 6181cc76-d376-11e9-a205-00163e20c49c
spec:
  containers:
  - args:
    - driver-py
    - --properties-file
    - /opt/spark/conf/spark.properties
    - --class
    - org.apache.spark.deploy.PythonRunner
    env:
    - name: SPARK_DRIVER_BIND_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SPARK_LOCAL_DIRS
      value: /var/data/spark-58c2dd88-e4d2-4f16-9381-531937827f9e
    - name: PYSPARK_PRIMARY
      value: hdfs:///user/hadoop/etlsdk/run.py
    - name: PYSPARK_MAJOR_PYTHON_VERSION
      value: "3"
    - name: PYSPARK_APP_ARGS
      value: data_pipeline.plugin_base.oss2hive.Oss2HivePlugin.run --config hdfs://apps/ETLPlatform/production/1711673/configs.json
    - name: PYSPARK_FILES
      value: file:///opt/spark/work-dir/data_pipeline.zip:file:///opt/spark/work-dir/etlsdk.zip
    - name: SPARK_CONF_DIR
      value: /opt/spark/conf
    image: registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline:test
    imagePullPolicy: Always
    name: spark-kubernetes-driver
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    resources:
      limits:
        memory: 1680Mi
      requests:
        cpu: "1"
        memory: 1680Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/data/spark-58c2dd88-e4d2-4f16-9381-531937827f9e
      name: spark-local-dir-1
    - mountPath: /opt/spark/conf
      name: spark-conf-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: spark-token-zr5xz
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: aliyun-registry
  nodeName: sa3.k8s.aipp.io
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: spark
  serviceAccountName: spark
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: spark-local-dir-1
  - configMap:
      defaultMode: 420
      name: datapipeline-1568084099332-driver-conf-map
    name: spark-conf-volume
  - name: spark-token-zr5xz
    secret:
      defaultMode: 420
      secretName: spark-token-zr5xz
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-09-10T02:55:00Z
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-09-10T02:56:14Z
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-09-10T02:55:00Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://eba2c1a8377c807eefb1ee5580df6c5702af99f3114b683a78c66764ac667829
    image: registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline:test
    imageID: docker-pullable://registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline@sha256:6755aaa3b4ee253a56be80ccbbcf3fd9ed0bc06ba62974f56c04a009e0b372e6
    lastState: {}
    name: spark-kubernetes-driver
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://eba2c1a8377c807eefb1ee5580df6c5702af99f3114b683a78c66764ac667829
        exitCode: 0
        finishedAt: 2019-09-10T02:56:13Z
        reason: Completed
        startedAt: 2019-09-10T02:55:51Z
  hostIP: 10.10.80.111
  phase: Succeeded
  podIP: 20.100.2.155
  qosClass: Burstable
  startTime: 2019-09-10T02:55:00Z
