apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-09-10T02:55:01Z
  name: {appname}-svc
  namespace: dev
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: {appname}
    uid: {uid}
  resourceVersion: "1542046"
  selfLink: /api/v1/namespaces/dev/services/{appname}-svc
spec:
  clusterIP: None
  ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  selector:
    spark-app-selector: {appid}
    spark-role: driver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
