apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 20.100.103.26/32
  creationTimestamp: "2019-09-25T11:43:29Z"
  labels:
    spark-app-selector: spark-b5bf94ba63bc4d1380a414eb759ea99b
    spark-role: driver
  name: data-pipeline-test-1569411807621-driver
  namespace: spark-dev
  resourceVersion: "172257193"
  selfLink: /api/v1/namespaces/spark-dev/pods/data-pipeline-test-1569411807621-driver
  uid: b1a1eec3-df89-11e9-96d8-00163f009e2e
spec:
  containers:
  - args:
    - driver-py
    - --properties-file
    - /opt/spark/conf/spark.properties
    - --class
    - org.apache.spark.deploy.PythonRunner
    env:
    - name: SPARK_DRIVER_BIND_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SPARK_LOCAL_DIRS
      value: /var/data/spark-0cf5d632-6e2f-46b1-b715-fcfa7d829038
    - name: PYSPARK_PRIMARY
      value: hdfs:///user/hadoop/etlsdk/run.py
    - name: PYSPARK_MAJOR_PYTHON_VERSION
      value: "3"
    - name: PYSPARK_APP_ARGS
      value: data_pipeline.plugin_base.oss2hive.Oss2HivePlugin.run --config hdfs://tmp/ting.wu/k8s_press/1740219.json
    - name: PYSPARK_FILES
    - name: SPARK_CONF_DIR
      value: /opt/spark/conf
    image: registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline:test_tee
    imagePullPolicy: Always
    name: spark-kubernetes-driver
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    resources:
      limits:
        memory: 1400Mi
      requests:
        cpu: "1"
        memory: 1400Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/data/spark-0cf5d632-6e2f-46b1-b715-fcfa7d829038
      name: spark-local-dir-1
    - mountPath: /tmp/log
      name: log
    - mountPath: /opt/spark/conf
      name: spark-conf-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: spark-token-k7l88
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: aliyun-registry
  nodeName: emr-work3-dev.node.k8s.aipp.io
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: spark
  serviceAccountName: spark
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: spark-local-dir-1
  - name: log
    persistentVolumeClaim:
      claimName: spark-dev-log
  - configMap:
      defaultMode: 420
      name: data-pipeline-test-1569411807621-driver-conf-map
    name: spark-conf-volume
  - name: spark-token-k7l88
    secret:
      defaultMode: 420
      secretName: spark-token-k7l88
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-25T11:43:29Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-09-25T14:30:35Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-25T11:43:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://70a7872b71d0f65024e81fbe2fe3586f6be73d05cd827719310a641db221c71d
    image: registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline@sha256:da2f46ccb27f0752927a06d9c7b6c620eb4d7371be45fc27c75f2f93dcbfe7e3
    imageID: docker-pullable://registry-vpc.cn-hangzhou.aliyuncs.com/eigenlab/data_pipeline@sha256:da2f46ccb27f0752927a06d9c7b6c620eb4d7371be45fc27c75f2f93dcbfe7e3
    lastState: {}
    name: spark-kubernetes-driver
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://70a7872b71d0f65024e81fbe2fe3586f6be73d05cd827719310a641db221c71d
        exitCode: 0
        finishedAt: "2019-09-25T14:30:34Z"
        reason: Completed
        startedAt: "2019-09-25T11:43:31Z"
  hostIP: 10.10.30.238
  phase: Succeeded
  podIP: 20.100.103.26
  qosClass: Burstable
  startTime: "2019-09-25T11:43:29Z"
