apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-25T11:43:29Z"
  name: data-pipeline-test-1569411807621-driver-svc
  namespace: spark-dev
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: data-pipeline-test-1569411807621-driver
    uid: b1a1eec3-df89-11e9-96d8-00163f009e2e
  resourceVersion: "172170857"
  selfLink: /api/v1/namespaces/spark-dev/services/data-pipeline-test-1569411807621-driver-svc
  uid: b1dd644b-df89-11e9-96d8-00163f009e2e
spec:
  clusterIP: None
  ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  selector:
    spark-app-selector: spark-b5bf94ba63bc4d1380a414eb759ea99b
    spark-role: driver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
